# Based on https://github.com/jaredlll08/MultiLoader-Template

# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=2.0.2
group=com.polpg.netherited
java_version=25

# Common
minecraft_version=26.1
mod_name=Netherited
mod_author=polpg
mod_id=netherited
license=CC0-1.0
credits=
description=This mod adds a new enchantment that prevents item from burning in fire and lava.
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1-1
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.11
parchment_version=2025.12.20

# Fabric
## https://fabricmc.net/develop/
fabric_version=0.144.0+26.1
fabric_loader_version=0.18.4
# https://modrinth.com/mod/modmenu/versions
modmenu_version=18.0.0-alpha.6

# NeoForge
## https://projects.neoforged.net/neoforged/neoforge
neoforge_version=26.1.0.1-beta
neoforge_loader_version_range=[4,)
minecraft_version_range=[26.1, 27.0)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
